# compose.yaml
services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    networks:
      - reseau
  api:
    build:
      context: ./rainign
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3000:3000
    environment:
      INFLUXDB_URL: http://influxdb:8086
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: rasp
    secrets:
      - influxdb2-admin-token
    networks:
      - reseau
    volumes:
      - ./rainign:/rainign
  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: database
    ports:
      - 8416:8416
    volumes:
      - /dev/shm/:/dev/shm/
    environment:
      INFLUXDB_URL: http://influxdb:8086
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: rasp
    secrets:
      - influxdb2-admin-token
    networks:
      - reseau
    depends_on:
      - influxdb
secrets:

  influxdb2-admin-username:
    file: ./.password/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./.password/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ./.password/.env.influxdb2-admin-token
volumes:
  influxdb2-data:
  influxdb2-config: 
networks:
  reseau:
    driver: bridge