# compose.yaml
services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: orgs
      DOCKER_INFLUXDB_INIT_BUCKET: rasp
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    networks:
      - reseau
  api:
    image: node:14
    container_name: api
    ports:
      - 3000:3000
    environment:
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
    secrets:
      - influxdb2-admin-token
    command: >
      bash -c "cd /rainign
      && npm install
      && npm run watch"
    networks:
      - reseau
    volumes:
      - ./rainign:/rainign

secrets:
  influxdb2-admin-username:
    file: ./.password/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./.password/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ./.password/.env.influxdb2-admin-token
volumes:
  influxdb2-data:
  influxdb2-config: 
networks:
  reseau:
    driver: bridge